name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - master
    paths:
      - 'cloudflare-worker/**'
  workflow_dispatch:

jobs:
  deploy-worker:
    runs-on: ubuntu-latest
    name: Deploy Turnstile Worker
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN}}
          workingDirectory: 'cloudflare-worker'
          secrets: |
            TURNSTILE_SECRET_KEY
        env:
          TURNSTILE_SECRET_KEY: ${{ secrets.TURNSTILE_SECRET_KEY }}